### ISSUE TITLE
熟悉官方区块浏览器的主要功能

### ISSUE THREAD

**Issue by shniu** [syphchain/blockchain-explorer#5]
- 参考  hyperledger/blockchain-explorer swagger.json
- 熟悉区块浏览器要做的事情
- 了解区块链基本原理

**Comment by shniu** [comment]
参考 fabric-sdk-node: https://fabric-sdk-node.github.io/release-1.3/index.html

**Comment by shniu** [comment]
重点研究一下官方是如何做区块信息同步的  @Siger2014 @lsyzy

**Comment by Siger2014** [comment]
该部分任务基本完成 后续在 #1 issue中继续跟进
